### ISSUE TITLE
Change Chapter Sorting

### ISSUE THREAD

**Issue by ryanthompson591** [AVeenstra/Images_To_ePub#1]
Thanks for making this super cool tool. I used it, but I made a change, because if my chapters were numbered they would get out of order.

Here is my change:

Where you have:
dirs = sorted(dirs)

I changed it to;
dirs.sort(key=natural_keys)

I added natural key generation up at the top of the file:
def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    '''
    http://nedbatchelder.com/blog/200712/human_sorting.html
    '''
    return [ atoi(c) for c in re.split(r'(\d+)', text) ]

This means instead of chapters being in order:
1,10,11,2,3,4,5,6,7,8,9
They will be:
1,2,3,4,5,6,7,8,9,10,11

**Comment by AVeenstra** [comment]
Thank you for sharing your change! I have added the natural sort to the new version.

Feel free to create new issues or pull requests!
