### ISSUE TITLE
Does the image in the e-book maintain the aspect ratio of the original image?

### ISSUE THREAD

**Issue by sword-huang** [AVeenstra/Images_To_ePub#2]
As title!

**Comment by AVeenstra** [comment]
Yes... or at least it should.
Feel free to reopen this issue if it does not work as advertised.

Note to future me: _The lines responsible for the resize are:_ https://github.com/AVeenstra/Images_To_ePub/blob/dfc4feba8932090db34da21fc9c9277843d92b5c/_ePubMaker.py#L210-L214
