### ISSUE TITLE
Bug in _ePubMaker?

### ISSUE THREAD

**Issue by sulph68** [AVeenstra/Images_To_ePub#3]
There might be a bug in ePubMaker Line 93?

The following original code doesn't work and results in an error.
`        self.template_env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), undefined=StrictUndefined)
`
```
Traceback (most recent call last):
  File "Images_To_ePub.py", line 93, in <module>
    EPubMaker(
  File "/home/copper/build/Images_To_ePub/_ePubMaker.py", line 94, in __init__
    self.template_env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), undefined=StrictUndefined)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```
but i corrected it with the below
`        self.template_env = Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)), undefined=StrictUndefined)
`

and the ePub processes OK.

**Comment by AVeenstra** [comment]
Thank you for taking the time to create this issue!

Could you update the Jinja package? The pathlib is quite recent (Python 3.4) and Jinja is old (2006ish), so I think you have a version of Jinja that does not yet support the cool pathlib module.

Please reopen this issue if needed. For example, if you can not update for whatever reason, or if my guess is wrong.
